### ISSUE TITLE
Not able to clone the repository

### ISSUE THREAD

**Issue by SanderClaus** [basespace/basespace-r-sdk#2]
Hi, 

I would like to install the package, but when I try to clone the repository (first step of installation) I get the following error: 

```
sclaus@ip-172-31-20-242:/store/opt/basespace-r-sdk$ sudo git clone git@github.com:basespace/basespace-r-sdk.git
Cloning into 'basespace-r-sdk'...
Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by adrianalexa** [comment]
Hi Sander, 
please use the BaseSpaceR source from the Bioconductor repository if you want the latest BaseSpaceR version. This repository is not up to date anymore. 

Best regards,
Adrian

**Comment by SanderClaus** [comment]
Thanks Adrian, I didn't know that.
